# config.yaml
# === Subject info ===
subinfo_fields:
  - name: subject_id
    type: int
    constraints:
      min: 101
      max: 999
      digits: 3


  - name: subname    
    type: string

  - name: age 
    type: int
    constraints:
      min: 5
      max: 60

  - name: gender
    type: choice
    choices: [Male, Female]

subinfo_mapping:
    subject_id: "被试号"
    subname: "被试姓名(拼音)"
    age: "年龄"
    gender: "性别"
    Male: "男"
    Female: "女"
    registration_failed: "注册失败。"
    registration_successful: "注册成功！"
    invalid_input: "字段 {field} 输入无效"


# === Window settings ===
window:
  size: [1920, 1080]
  units: deg
  screen: 1
  bg_color: gray
  fullscreen: True
  monitor_width_cm: 60
  monitor_distance_cm: 72

# === Task-level settings ===
task:
  task_name: "flanker"
  language: "Chinese"
  voice_name: "zh-CN-YunyangNeural"
  total_blocks: 3
  total_trials: 180 # 3 blocks * 60 trials/block
  trial_per_block: 60 # 15 of each of 4 conditions
  conditions: [congruent_left, congruent_right, incongruent_left, incongruent_right]
  key_list: [f, j]
  left_key: f
  right_key: j
  seed_mode: "same_across_sub"

# === Stimuli ===
stimuli:
  fixation:
    type: text
    text: "+"
    color: white
    height: 1.5

  congruent_left:
    type: text
    text: "<<<<<"
    color: white
    height: 1.5
  congruent_right:
    type: text
    text: ">>>>>"
    color: white
    height: 1.5
  incongruent_left:
    type: text
    text: ">><>>"
    color: white
    height: 1.5
  incongruent_right:
    type: text
    text: "<<><<"
    color: white
    height: 1.5

  correct_feedback:
    type: text
    text: "正确"
    color: "green"
    font: SimHei
    height: 1.5
  incorrect_feedback:
    type: text
    text: "错误"
    color: "red"
    font: SimHei
    height: 1.5
  no_response_feedback:
    type: text
    text: "未反应"
    color: "orange"
    font: SimHei
    height: 1.5

  block_break:
    type: text
    text: |
      第 {block_num} / {total_blocks} 部分完成
      正确率：{accuracy:.2%}
      
      请在充分休息后按【空格键】继续
    color: white
    height: 1.5

  instruction_text:
    type: textbox
    text: |
      【Flanker任务】
      
      任务开始后，屏幕中央会显示一个“+”号，请注视它。
      随后，会出现一排箭头（例如 >>>>> 或 >><>>）。
      请您尽快判断中间箭头的朝向。
      
      如果中间箭头朝向左（<），请按【f】方向键。
      如果中间箭头朝向右（>），请按【j】方向键。
      
      请只关注中间的箭头，忽略两边的箭头。
      
      准备好后，请按【空格键】开始。
    color: white
    font: SimHei
    alignment: center
    letterHeight: 0.78
    units: deg
    size: [20, 5]

  good_bye:
    type: text
    text: "实验结束，感谢您的参与！"
    color: white
    height: 1.5

# === Timing ===
timing:
  iti_duration: [0.8, 1.2] # Inter-trial interval (randomized)
  # === Duration settings ===
  fixation_duration: 0.5
  stim_duration: 1.0  # Max time for response
  feedback_duration: 0.5

# === Triggers ===
triggers:
  exp_onset: 98
  exp_end: 99

  block_onset: 100
  block_end: 101

  fixation_onset: 1
  
  congruent_stim_onset: 10
  incongruent_stim_onset: 20
  
  left_key_press: 30
  right_key_press: 31
  
  feedback_correct_response: 51
  feedback_incorrect_response: 52
  feedback_no_response: 53
  
  feedback_onset: 60



